#!/usr/bin/env bash
# Transfers a file from our client to a server

if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file=$1
ip=$2
user=$3
key=$4

scp -o StrictHostKeyChecking=no -i "$key" "$file" "$user@$ip:~/"

if [ "$?" -eq 0 ]; then
    echo "File transfer successful."
else
    echo "File transfer failed."
    exit 1
fi
