#!/usr/bin/env bash
# Configure nginx server redirecting to another page
sudo apt-get update
sudo apt-get -y install nginx

# Define the new line to be added for redirection
redirection_rule="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

# Insert the redirection rule into the Nginx configuration file
sudo sed -i "53i $redirection_rule" /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart
